# 服务端口配置
server:
  port: ${port:8080}
  servlet:
    context-path: ${context-path:/}

spring:
  application:
    name: ${appName:template-app}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# log 配置
logging:
  config: classpath:logback-spring.xml
  # log level
  level:
    root: debug